apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "osc-mcp.name" . }}
  labels:
    {{- include "osc-mcp.labels" . | nindent 4 }}
{{- with .Values.global.imagePullSecrets }}
imagePullSecrets:
  {{- tpl (toYaml .) $ | nindent 2 }}
{{- end }}
